baseurl = "https://unsignedpixel.com/blog/"
#url = "https://unsignedpixel.com/"
languageCode = "en-us"
title = "unsigned pixel"
theme = "casper"
paginate = 15
#paginatePath = "/blog/page/"
[permalinks]
post = "/:year/:month/:title/"
page = "/:slug/"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120

[[menu.main]]
pre = "<h6>projects</h6>"
identifier = "projects"
name = "Podcast Connection"
url = "/podcast connection"
[[menu.main]]
name = "yet another filmroll app"
url= "/YAFRA"
[[menu.main]]
name = "Straight Camera"
url= "/straight camera"
[[menu.main]]
pre = "<h6>info</h6>"
weight = 101
name = "My photography"
url = "http://christianscheer.com"


[params]
author = "Chris"
authorlocation = "Dortmund, Germany"
authorwebsite = "http://christianscheer.com"
bio = "iOS development and more"
#cover = "images/cover_polenord.jpg"
#cover is the large image on the front page, we need a pic of my hands typing while wearing a cool t-shirt
cover = "images/20160606_IMG_5498.jpg"
description = "coding for your and my photography needs"
githubName = "unsignedpixel"

hideHUGOSupport = false
#logo = "images/logo.png"
logo = "images/unsigned_06.svg"
twitterName = "chris5s"
#[permalinks]

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
