baseurl = "http://unsignedpixel.com/blog/"
url = "http://unsignedpixel.com"
languageCode = "en-us"
title = "unsigned pixel"
theme = "casper"

[permalinks]
post = "/:year/:month/:title/"
page = "/:slug/"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
pre = "<h6>projects</h6>"
name = "Podcast Connection"
url = ""
[[menu.main]]
name = "yet another filmroll app"
url= ""
[[menu.main]]
name = "Straight Camera"
url= ""
[[menu.main]]
pre = "<h6>info</h6>"
weight = 101
name = "My photography"
url = "http://christianscheer.com"


[params]
author = "Chris"
authorlocation = "Dortmund, Germany"
authorwebsite = "http://christianscheer.com"
bio = "iOS development and more"
#cover = "images/cover_polenord.jpg"
#cover is the large image on the front page, we need a pic of my hands typing while wearing a cool t-shirt
cover = "pic that is not available"
description = "coding for your and my photography needs"
githubName = "unsignedpixel"

hideHUGOSupport = false
#logo = "images/logo.png"
logo = "img/unsigned_06.svg"
twitterName = "chris5s"
#[permalinks]

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
